In [1]:
import pandas as pd

In [2]:
# to access data from a csv file we've given it the variable name data
# using the pandas Library the read_csv() function it accesses the data
data = pd.read_csv('customers.csv')

In [3]:
# we can print the first five rows of data using
# the built in python function head()
data.head()

,Customer Id,Customer Name,VIN,Location,Street Address,State,City,Zip,Phone,Email
0,CUS1008,Silvia Stone,1GCBS1941RP397653,Glen Allen,123 Nope Dr,VA,Glen Allen,23060,8043462277,SilviaStone@yahoo.com
1,CUS1009,Billy Kid,1GCBS1941LK397654,Midlothian,234B Leafy St,VA,Midlothian,23114,8043797264,Billy_Kid@gmail.com
2,CUS1014,Rita Skeeter,1GCBS1943FK397789,Woodbridge,2343 Blanco,VA,Woodbridge,22192,7035766550,RitaSkeeter@aol.com
3,CUS1015,Alastor Moody,1GKBS1941RK367993,Fredericksburg,643 Warzbach PKWY,VA,Fredericksburg,22407,5407107781,Alastor23@gmail.com
4,CUS1016,Pansy Parkinson,1GCRS197FGK396789,Brandywine,912 Silver Sands Dr,MD,Brandywine,20613,3017822942,PParkinson@gmail.com